
Welcome-Message: CaClHi c6cl{player}, CbClWelcome to unknow server!
#TitleMessage: Not complete right now!
Try-to-reload-to-player: CcTrying to reload...
Try-to-reload-to-console: C6clplayer} Cchas try to reload config! #When /jtagbrel Will broadcast to console
Reload-Complete: CaClReload Complete! #Reload Complete
# Placeholder C Can replace as &