# #######################################################################
# #                                                                     #
# #                      JoinCommands                                   #
# #                                                                     #
# #  Author: GalaxySMediaXz                                             #
# # Version: 0.2Snapshot                                                #
# #                                                                     #
# #######################################################################

Welcome-Message: Hi {player}, Welcome to unknow server! # You can add color code! Using ANSI Encoding!
Try-to-reload-to-player: Trying to reload JoinMessages...
Try-to-reload-to-console: {player} Trying to reload JoinMessages
Reload-Complete: Reload Configuration Complete!
